# Generated by Django 3.2.6 on 2021-09-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.ManyToManyField(blank=True, null=True, related_name='variant', to='product.Gender'),
        ),
    ]
