# Generated by Django 3.2.6 on 2021-09-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='attribute',
        ),
        migrations.AddField(
            model_name='category',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='product.attribute'),
        ),
    ]
